name: Build APK and IPA
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest   # لازم macOS علشان iOS build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter 3.32.0
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Install dependencies
        run: flutter pub get

      # Android build
      - name: Build APK
        run: flutter build apk --release

      # iOS build (IPA)
      - name: Build iOS IPA
        run: flutter build ipa --release --no-codesign

      - name: Read App Name
        id: read_apk_name
        run: |
          APP_NAME=$(cat assets/app/name.txt)
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT

      - name: Prepare release files
        run: |
          mkdir -p release_files
          cp build/app/outputs/flutter-apk/app-release.apk release_files/${{ steps.read_apk_name.outputs.app_name }}.apk
          cp build/ios/ipa/*.ipa release_files/${{ steps.read_apk_name.outputs.app_name }}.ipa

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-builds
          path: release_files/

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Mobile App Release"
          tag_name: "v1.0.${{ github.run_number }}"
          files: release_files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
