name: Build Android & iOS

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1- سحب الكود
      - name: Checkout code
        uses: actions/checkout@v3

      # 2- اختيار أحدث Xcode متاح
      - name: Use latest stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      # 3- تهيئة Java
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4- تثبيت Flutter
      - name: Install Flutter 3.32.0
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      # 5- تحميل الـ dependencies
      - name: Install dependencies
        run: flutter pub get

      # 6- بناء APK
      - name: Build APK
        run: flutter build apk --release

      # 7- إنشاء ExportOptions.plist (لإخراج IPA بدون توقيع)
      - name: Create ExportOptions.plist
        run: |
          cat > ios/ExportOptions.plist <<EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOL

      # 8- بناء iOS IPA بدون توقيع + تصدير
      - name: Build iOS IPA
        run: flutter build ipa --release --no-codesign --export-options-plist=ios/ExportOptions.plist

      # 9- قراءة اسم التطبيق من name.txt
      - name: Read App Name
        id: read_app_name
        run: |
          APP_NAME=$(cat assets/app/name.txt)
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT

      # 10- تجهيز الملفات للإصدار
      - name: Prepare release files
        run: |
          mkdir -p release_files
          cp build/app/outputs/flutter-apk/app-release.apk release_files/${{ steps.read_app_name.outputs.app_name }}.apk
          cp build/ios/ipa/*.ipa release_files/${{ steps.read_app_name.outputs.app_name }}.ipa

      # 11- رفع الملفات كـ Artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-builds
          path: release_files/

      # 12- رفع الملفات على GitHub Release
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Mobile App Release"
          tag_name: "v1.0.${{ github.run_number }}"
          files: release_files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
