name: Build iOS IPA (No Signing, Auto ExportOptions)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1- جلب الكود
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2- تثبيت Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2" # عدل حسب نسختك

      # 3- تحميل الحزم
      - name: Flutter Pub Get
        run: flutter pub get

      # 4- تثبيت CocoaPods
      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          cd ..

      # 5- إنشاء ExportOptions.plist مؤقت
      - name: Create ExportOptions.plist
        run: |
          cat > ios/ExportOptions.plist <<EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
              "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOL

      # 6- بناء المشروع بدون توقيع
      - name: Flutter Build iOS (No Signing)
        run: flutter build ios --release --no-codesign

      # 7- إنشاء Archive
      - name: Create Archive
        run: |
          mkdir -p build/ios/archive
          xcodebuild archive \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            CODE_SIGNING_ALLOWED=NO

      # 8- تصدير ملف IPA
      - name: Export IPA (Unsigned)
        run: |
          mkdir -p build/ios/ipa
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO || true

      # 9- رفع الـ IPA كـ Artifact
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa-unsigned
          path: build/ios/ipa/*.ipa
