name: Build Flutter App (Android & iOS)
on:
  push: 
    branches:
      - main
permissions:
  contents: write
jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build Android APK

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Read APK name from name.txt
        id: read_apk_name
        run: |
          APK_NAME=$(cat assets/app/name.txt)
          echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT

      - name: Rename APK and move to apk_release/
        run: |
          mkdir -p apk_release
          cp build/app/outputs/flutter-apk/app-release.apk apk_release/${{ steps.read_apk_name.outputs.apk_name }}.apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: apk_release/${{ steps.read_apk_name.outputs.apk_name }}.apk

  build-ios:
    runs-on: macos-13
    name: Build iOS App

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Check available iOS SDKs
        run: xcodebuild -showsdks | grep iOS

      - name: Check for required secrets
        id: check_secrets
        run: |
          if [ -z "${{ secrets.BUILD_CERTIFICATE_BASE64 }}" ] || [ -z "${{ secrets.P12_PASSWORD }}" ] || [ -z "${{ secrets.BUILD_PROVISION_PROFILE }}" ] || [ -z "${{ secrets.DEVELOPMENT_TEAM }}" ]; then
            echo "::warning::One or more required secrets are missing. Building for simulator instead."
            echo "USE_SIMULATOR=true" >> $GITHUB_ENV
          else
            echo "USE_SIMULATOR=false" >> $GITHUB_ENV
          fi

      - name: Setup code signing (for real devices)
        if: env.USE_SIMULATOR == 'false'
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE: ${{ secrets.BUILD_PROVISION_PROFILE }}
        run: |
          set -e
          
          # Create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          
          # Check if certificate exists and is valid
          if [ -z "$BUILD_CERTIFICATE_BASE64" ]; then
            echo "::error::BUILD_CERTIFICATE_BASE64 is empty"
            exit 1
          fi
          
          # Import certificate and provisioning profile from secrets
          echo "$BUILD_CERTIFICATE_BASE64" | base64 --decode > $CERTIFICATE_PATH || {
            echo "::error::Failed to decode certificate"
            exit 1
          }
          
          echo "$BUILD_PROVISION_PROFILE" | base64 --decode > $PP_PATH || {
            echo "::error::Failed to decode provisioning profile"
            exit 1
          }
          
          # Create and unlock keychain
          security create-keychain -p "" $KEYCHAIN_PATH || true
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "" $KEYCHAIN_PATH
          
          # Import certificate to keychain
          security import $CERTIFICATE_PATH \
            -P "$P12_PASSWORD" \
            -A \
            -t cert \
            -f pkcs12 \
            -k $KEYCHAIN_PATH || {
              echo "::error::Failed to import certificate to keychain"
              exit 1
            }
            
          security set-key-partition-list -S apple-tool:,apple: -k "" $KEYCHAIN_PATH
          
          # Apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles/
          
          # Set environment variables for code signing
          echo "CODE_SIGNING_REQUIRED=YES" >> $GITHUB_ENV
          echo "DEVELOPMENT_TEAM=${{ secrets.DEVELOPMENT_TEAM }}" >> $GITHUB_ENV
          
      - name: Build iOS for simulator
        if: env.USE_SIMULATOR == 'true'
        run: |
          echo "Building for iOS simulator..."
          flutter build ios --simulator --no-codesign
          
          # Create output directory
          mkdir -p ios_build
          
          # Copy the app bundle
          if [ -d "build/ios/iphonesimulator/Runner.app" ]; then
            cd build/ios/iphonesimulator
            zip -r ../../../ios_build/Runner.app.zip Runner.app
          fi
          
      - name: Build iOS for device
        if: env.USE_SIMULATOR == 'false'
        run: |
          echo "Building for iOS device..."
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
          
          # Create output directory
          mkdir -p ios_build
          
          # Copy the IPA file
          if [ -f "build/ios/ipa/*.ipa" ]; then
            cp build/ios/ipa/*.ipa ios_build/
          fi

      - name: List build output
        run: find build/ios -name "*.ipa" -o -name "*.app" -type f

      - name: Verify build output
        run: |
          if [ "$USE_SIMULATOR" = "true" ]; then
            if [ ! -f "ios_build/Runner.app.zip" ]; then
              echo "::error::Simulator build failed: Runner.app.zip not found"
              exit 1
            fi
            echo "Simulator build successful"
          else
            if [ ! -f "ios_build/Runner.ipa" ]; then
              echo "::error::Device build failed: Runner.ipa not found"
              exit 1
            fi
            echo "Device build successful"
          fi

      - name: Upload iOS build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.USE_SIMULATOR == 'true' && 'ios-simulator-build' || 'ios-device-build' }}
          path: ios_build/
          if-no-files-found: error

  build-windows:
    runs-on: windows-latest
    name: Build Windows App

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows executable
        run: flutter build windows --release

      - name: Create Windows build directory
        run: New-Item -ItemType Directory -Force -Path windows_build
        shell: pwsh

      - name: Read app name for Windows exe
        id: read_exe_name
        run: |
          $APP_NAME = Get-Content assets/app/name.txt
          echo "exe_name=$APP_NAME" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Copy Windows executable and dependencies
        run: |
          New-Item -ItemType Directory -Force -Path windows_build
          Copy-Item -Recurse build/windows/x64/runner/Release/* windows_build/
          Rename-Item -Path "windows_build\my_app.exe" -NewName "${{ steps.read_exe_name.outputs.exe_name }}.exe"
        shell: pwsh

      - name: Upload Windows build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: windows_build/

  create-release:
    runs-on: ubuntu-latest
    needs: [build-android, build-ios, build-windows]
    name: Create GitHub Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read APK name from name.txt
        id: read_apk_name
        run: |
          APK_NAME=$(cat assets/app/name.txt)
          echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT

      - name: Download Android APK
        uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: release/

      - name: Download iOS build
        uses: actions/download-artifact@v4
        with:
          name: ios-app
          path: release/ios/

      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: windows-app
          path: release/windows/

      - name: Create Windows archive
        run: |
          cd release/windows
          zip -r ../windows-app.zip .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Mobile App Release v1.0.${{ github.run_number }}"
          tag_name: "v1.0.${{ github.run_number }}"
          files: |
            release/${{ steps.read_apk_name.outputs.apk_name }}.apk
            release/ios/Runner.ipa
            release/windows-app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
